services:
  - type: web
    name: telegram-file-transfer-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_master.py
    healthCheckPath: /